        throws IOException
    {
        try
        {
            in.close();
        }
        catch(IOException e)
        {
            handleIOException(e);
        }
