        try
        {
            in.reset();
        }
        catch(IOException e)
        {
            handleIOException(e);
        }
    }

