            }
        } catch (Exception e)
        {
            log.error("", e);
        }
        return ret;
    }
}
